### ISSUE TITLE
Consider relicensing samples as MIT/Apache/Non-copyleft OSS License du jour

### ISSUE THREAD

**Issue by 333fred** [Remora/Remora.Discord#232]
### Description

I don't have a problem with the main library itself being (L)GPL. However, the samples of how to actually use the library being LGPL is a problem for users. As it currently stands, the samples are the only real source of information on how to use Remora, and anyone who uses them is going to run into the issue (whether they realize it or not) that their code must be licensed (L)GPL if they use the samples as a reference.

### Why This is Needed

Allows people to learn the library without your license being foisted on them.

### Alternatives Considered

My current alternative is to use a different library.

**Comment by AraHaan** [comment]
My bot is licensed as MIT anyways, because I ignore the roles of LGPL. Besides Anyone can do the same as AFAIK who cares about licensing when most of us are not lawyers anyway.

Although then again we could ask @Nihlus if he could consider adopting the WTF pl or ``Do what the f*ck you want public license.`` As then it's compatible with all licenses.

**Comment by 333fred** [comment]
> Basically what I am saying is that, I do what the f*ck I want when it comes to selecting a license for my code as it's my code, and ignore licenses for all dependencies.

Perhaps don't admit on a public forum that you break international IP laws?

**Comment by AraHaan** [comment]
Technically it's not breaking an IP law if the code to it is also open source. Besides .NET itself is licensed under mit but lists the licenses of dependencies (that is not MIT) under a separate file.

**Comment by 333fred** [comment]
> Besides .NET itself is licensed under mit but lists the licenses of dependencies (that is not MIT) under a separate file.

It complies with the terms of all of its dependencies. And no, it definitely is breaking IP law. That's the whole point of the license.

> I think a few of those dependencies are also LGPL or GPL as well.

LGPL, possibly, as you can link to them without needing to be (L)GPL yourself. But definitely not GPL. Let's keep this on topic, and not debate other things.

**Comment by AraHaan** [comment]
Alright then, let's all agree on a license that states that "We do not care about the licenses of our dependencies, we just want to use them."

**Comment by 333fred** [comment]
> Alright then, let's all agree on a license that states that "We do not care about the licenses of our dependencies, we just want to use them."

No. I'm not asking for Remora to be relicensed. I'm only asking for the samples to be relicensed. And for the love of everything please stop admitting to breaking IP law.

**Comment by Nihlus** [comment]
@AraHaan I've been incredibly patient with you, far beyond what one could reasonably expect. You are no longer welcome on the Remora server or on the repositories. Start using your head and minding what comes out of your mouth.

**Comment by Nihlus** [comment]
As for the actual topic, I hear and understand the concerns and I'll give it some honest thought.

However, I don't appreciate the tone used when the issue was initially raised on the C# Discord, nor the responses that followed from other members. This is a pattern I've seen again and again over several years related to my decision to use GPL-family licenses, and I have very little patience left for it. I'm not interested in discussing that choice or the merits of the licenses here; that's for another topic and another time.

**Comment by 333fred** [comment]
> However, I don't appreciate the tone used when the issue was initially raised on the C# Discord

I apologize if I came off short or rude. That was not my intention. I was merely trying to point out an issue that I saw when trying to use the library for my MIT-licensed bot.

**Comment by Tylertron1998** [comment]
I definitely agree with the sentiment here; samples are just pointers and it's often very easy to just copy paste in some sample code, to test that everything runs alright, and then make small, incremental modifications going forward.

It also raises an interesting side note - how about things shared over discord; or samples on the [repository pages](https://remora.github.io/Remora.Discord/)? The general consensus for stuff like that is "you can take this for free; no ramifications" - while assumptions are risky to take when it comes to licences; or any legal matter - I think most would agree that "hey, this is how you do this" is generally free in that regard.

While I can completely understand licencing actual Remora code in any way you can see fit - as you (and many others) have put a LOT of effort into them; samples to me are just an added side benefit, a nice to have, in a way.

I'll be following this with great interest.

**Comment by Hamsterland** [comment]
It could be worth simply moving the samples to another repository (with its own license), if you don't want license clutter or confusion on Remora.Discord.

**Comment by VelvetThePanda** [comment]
I second this, it's what we do on [DSharpPlus](https://github.com/DSharpPlus/Example-Bots).

**Comment by 333fred** [comment]
Let me clarify why I think the current licensing setup has an issue:

Currently, all available documentation on certain parts of the library, such as `Remora.Discord.Interactivity`, is only available via a source licensed LGPL (either the samples, or the nested README in this repository). The purpose of user documentation is to be a reference for users when using a piece of software, and it's hard to argue that such a work is not a "derivative" of the sample or documentation, especially since samples or reference documentation are often copy/pasted and then modified slightly to work in the scenario the user is trying to accomplish. This would be ok if I were not intending on distributing my bot in any source or binary fashion, but I am planning on pushing my source to GitHub. This is a form of distribution, and thus my bot, a derivative work of the samples/README documentation, must abide by the license terms of those works, meaning I must at least license it LGPL. For my little bot, that's honestly probably not a huge deal, but it may be a problem for any larger bots that want to use Remora. In effect, it means that I must fully explore the API without looking at official documentation sources, or I must license my bot LGPL. In other words, the effect is the same as just licensing Remora under the full GPL v2 or v3 license in the first place.

**Comment by Nihlus** [comment]
Fixed. I also added a quick note to the main README about the code contained within documentation files as well.
