### ISSUE TITLE
[Bug]: Verifying the minvalue or maxvalue attributes always fails when using floating point params

### ISSUE THREAD

**Issue by murl-digital** [Remora/Remora.Discord#234]
### Description

When setting up a slash command with a floating point parameter (say a float, double, or decimal) and you add a MinValue or MaxValue attribute, building the command tree fails with the error message `A non-numerical parameter may not specify a minimum or maximum value.`. The problem is with CommandTreeExtensions, line 611.

### Steps to Reproduce

- Create a slash command with a float or double parameter with a MinValue or MaxValue attribute.
- Attempt to check slash commands support and/or update commands
- Observe that the mentioned error message is thrown unless the attributes are removed.

### Expected Behavior

The error should not be thrown, allowing the command tree to be built. (Barring any other issues with the registered commands)

### Current Behavior

The error message mentioned in the description is returned: `A non-numerical parameter may not specify a minimum or maximum value.`

### Library / Runtime Information

.NET 6.0.8
Remora.Discord 2022.48

**Comment by murl-digital** [comment]
Since I've already done the investigation, I'm more than happy to submit a PR for this myself.

**Comment by MazeXP** [comment]
Maybe also test cases for the MinSize and MaxSize attributes should be added similiar to the valid
MinLength and MaxLength tests for String parameters.


Reference for test:
- https://github.com/Remora/Remora.Discord/blob/main/Tests/Remora.Discord.Commands.Tests/Extensions/CommandTreeExtensionTests.cs#L665-L686
- https://github.com/Remora/Remora.Discord/blob/main/Tests/Remora.Discord.Commands.Tests/Data/Valid/StringParameterWithLengthConstraints.cs
