### ISSUE TITLE
[Bug]: IMessageCreate.Content is an empty string unless the bot is mentioned

### ISSUE THREAD

**Issue by Cyberboss** [Remora/Remora.Discord#236]
### Description

Right in the title. Mentioning the bot in a message populates the contents. 

### Steps to Reproduce

1. Implement `IResponder<IMessageCreate>`
2. Send text message that doesn't mention bot
3. Content is `""`

### Expected Behavior

Content populated for all `IMessageCreate` events.

### Current Behavior

Content only populated for `IMessageCreate`s that mention the bot.

### Library / Runtime Information

net6.0
Nuget Version="2022.48.0"

**Comment by Cyberboss** [comment]
Workaround:

```cs
var refreshedMessage = !String.IsNullOrWhiteSpace(messageCreateEvent.Content)
				? messageCreateEvent
				: (await channelsClient.GetChannelMessageAsync(messageCreateEvent.ChannelID, messageCreateEvent.ID, cancellationToken)).Entity;
```

**Comment by Nihlus** [comment]
In order to receive message contents from Discord, you have to enable the MessageContents intent and flip a switch in your bot's application panel. This is not a Remora issue.

https://discord.com/developers/docs/topics/gateway#message-content-intent

**Comment by Cyberboss** [comment]
This switch is flipped for the bot in question which is why I was wondering if this was an API change in the latest Remora.

Downgrading to 5.0.0 fixed it

**Comment by Nihlus** [comment]
Yes, that's because that version uses an older gateway version where the intent is enabled by default on Discord's side. You need to enable the intent in your code - see https://github.com/Remora/Remora.Discord/blob/main/Samples/SlashCommands/Program.cs#L105

**Comment by Cyberboss** [comment]
Appreciated, ty.
