### ISSUE TITLE
[Bug]: XML documentation is absent

### ISSUE THREAD

**Issue by Kaoticz** [Remora/Remora.Discord#249]
### Description

XML documentation is not shown by intellisense's preview when hovering over types, methods, or anything defined in `Remora.Discord`. This seems to affect all versions from 2022.47.0 onwards, as 2022.46.0 and older versions are not affected by this.

The cause could be the removal of `<GenerateDocumentationFile>` from `Directory.Build.props` in [this commit](https://github.com/Remora/Remora.Discord/commit/f5b03d06ac316b57d936a5d7295e7b8864edf2e2#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eL58).

### Steps to Reproduce

- Install `Remora.Discord` 2022.46.0
- Hover over any type or method provided by the libraries in `Remora.Discord` and look at the preview window generated by your IDE. It should have the proper documentation.
- Now install `Remora.Discord` 2022.47.0 or any newer version.
- Hover again and now the documentation is gone.

### Expected Behavior

The preview should contain documentation for the type/method.
Example:
![rem-good](https://user-images.githubusercontent.com/1812311/199840491-e9aff267-cee7-443b-99c9-82d5db57958f.png)

### Current Behavior

The preview contains no useful information.
Example:
![rem-bad](https://user-images.githubusercontent.com/1812311/199840545-ea1fac20-d0c2-4406-8a3a-a7ca213ad02b.png)

### Library / Runtime Information

.NET: 6.0.110
Remora.Discord: 2022.49.0

**Comment by Nihlus** [comment]
`GenerateDocumentationFile` is still set to `true` via Remora.Sdk - perhaps it's placement sensitive, in which case this is an issue that should be moved to Remora.Sdk.

**Comment by MazeXP** [comment]
This one is fixee
