### ISSUE TITLE
Fall back to default command trees when the command is not found.

### ISSUE THREAD

**Issue by yretenai** [Remora/Remora.Discord#258]
### Description

It was deprecated in this commit: https://github.com/Remora/Remora.Discord/commit/c0477dfcff9b0e7bb7d0dff236ca6fb27276e4d1 without explanation on _why_ it was removed.

Though it's current state in 2202.49 is broken since InteractionResponder.TryExecuteCommand casts [a Result into a Result](https://github.com/Remora/Remora.Discord/blob/2022.49/Remora.Discord.Commands/Responders/InteractionResponder.cs#L206) which will [set the success state to true (rather than preserving the existing result state)](https://github.com/Remora/Remora.Results/blob/b14470ad11a749e92f3cbaabbfcc0999a6e6b860/Remora.Results/Result.cs#L363-L371), even if this behavior was not what was observed it will retry with [the same treeName](https://github.com/Remora/Remora.Discord/blob/2022.49/Remora.Discord.Commands/Responders/InteractionResponder.cs#L167) -- this will make it successfully fail with a CommandNotFound result and the default tree will never be evaluated (see below.) I initially was going to report this as a bug but that's when I found the removal commit. **This exact bug is happening all over the project. Every time a Result\<T\> is cast to Result, it will be successfull**

![Screenshot_20221130_014405](https://user-images.githubusercontent.com/614231/204812046-2ad123dd-b260-459b-83c9-7881b1b2bf42.png)

### Why This is Needed

I am designing a system where certain command groups are opt-in.

### Alternatives Considered

Specifying the command groups used in the global tree in the named trees (i.e. merging the two trees,) results in Discord showing the commands twice in the command list. (See attached image below)

![Screenshot_20221130_012736](https://user-images.githubusercontent.com/614231/204811813-7c06c053-c375-4eb7-a02d-e1c1546588d2.png)

Rejecting the command on the "command level" still shows it in the command list and will leave a dangling interaction or response message behind.

### Additional Details

Ultimately I ended up writing my own Interaction Responder which runs through a list of trees rather than just one + default.

**Comment by VelvetThePanda** [comment]
(Actually, I just realized this image is technically inaccurate, oops, but the main gist is still correct.)

**Comment by Nihlus** [comment]
Is the content of the issue valid, since you closed it? The body of the described problems suggest more than one issue, but it's unclear which (if any) are moot or resolved.
