### ISSUE TITLE
[Bug]: Conditions are evaluated before having a CommandContext

### ISSUE THREAD

**Issue by MazeXP** [Remora/Remora.Discord#262]
### Description

Currently any condition by Remora.Discord itself is causing an `InvalidOperationException`.

Reported by Patrick on Discord: https://discord.com/channels/789912892426027039/789913038920744960/1051957624884695152

### Steps to Reproduce

Just add `[RequireDiscordPermission]` on any command.

### Expected Behavior

The condition to be evaluated correctly.

### Current Behavior

An `InvalidOperationException` is being thrown when the condition should actually be evaluated.
```
[20:23:26 WRN] Error in gateway event responder: No context has been set for this scope.
System.InvalidOperationException: No context has been set for this scope.
   at Remora.Discord.Commands.Extensions.ServiceCollectionExtensions.<>c.<AddDiscordCommands>b__1_1(IServiceProvider s)
```

### Library / Runtime Information

**Remora.Discord:** 2022.50.0

**Comment by MazeXP** [comment]
**Analysis**

The cause for the exception is that during the evaluation of conditions in Remora.Commands, we do not have an `ICommandContext` in scope yet. [[link]](https://github.com/Remora/Remora.Discord/blob/main/Remora.Discord.Commands/Responders/InteractionResponder.cs#L149)
We do only either have an `IMessageContext` or `IInteractionContext`, because `ICommandContext` will only be available after the command has been prepared. [[link]](https://github.com/Remora/Remora.Discord/blob/main/Remora.Discord.Commands/Responders/InteractionResponder.cs#L187)

**Possible solutions**
1. Do not use `ICommandContext` in conditions, but `IOperationContext` and match on `IMessageContext` and `IInteractionContext`.
2. Change `Remora.Commands` to evaluate conditions in `TryExecuteAsync` instead of `TryPrepareCommandAsync`.

**Comment by Nihlus** [comment]
Thank you for the report! I'm going to switch them (and some of the parsers) over to `IOperationContext` instead, since they don't actually require command information to function.

**Comment by patrickklaeren** [comment]
The fix for this in https://github.com/Remora/Remora.Discord/commit/390ddbfbff08ecb2dfbbd05dee05d49272b67c3a

Has fixed the underlying exception, but now is defaulting the User ID to `0`.

```
[19:20:11 INF] Sending HTTP request GET https://discord.com/api/v10/guilds/532257124131012640/members/0
info: System.Net.Http.HttpClient.RestHttpClient<RestError>.ClientHandler[101]
      Received HTTP response headers after 168.4273ms - 404
```

Likely here:

https://github.com/Remora/Remora.Discord/blob/390ddbfbff08ecb2dfbbd05dee05d49272b67c3a/Remora.Discord.Commands/Conditions/RequireDiscordPermissionCondition.cs#L102-L107 

I'm running as a member within a guild. Member => User.

**Comment by Nihlus** [comment]
Is this with an interaction or a text command?

**Comment by patrickklaeren** [comment]
Slash command, so interaction I suppose

**Comment by Nihlus** [comment]
Gotcha; one moment.

**Comment by Nihlus** [comment]
Should be fixed now - I added a couple of helper extensions for extracting user/channel/guild IDs when you don't really care about the context type.

**Comment by patrickklaeren** [comment]
Haha; I did the same a day ago.

**Comment by patrickklaeren** [comment]
Confirmed fix in .52
