### ISSUE TITLE
[Bug]: ResponderDispatchService.DisposeAsync() can deadlock

### ISSUE THREAD

**Issue by Cyberboss** [Remora/Remora.Discord#305]
### Description

The `_finalizer` `Task` relies on the `_dispatcher` `Task` closing the channel to be able to complete. But it's possible for this to never happen. 

The [channel completion call](https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L168) relies on several throws possible from the CancellationToken _not_ happening.
- https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L143
- https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L151
- https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L165

The deadlock is usually avoided because the `_finalizer` `Task` also usually throws out before it gets to that point
- https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L188-L191
- https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L202

All the lines listed can throw `TaskCanceledException`s. The deadlock occurs if **any** of the first group throw and **none** of the second group throw. At that point, the app will halt forever when it [awaits the Reader's completion](https://github.com/Remora/Remora.Discord/blob/1f248a4b5bcd4c4b19e78329378cd49ce4510464/Backend/Remora.Discord.Gateway/Services/ResponderDispatchService.cs#L210).

### Steps to Reproduce

It's very difficult to reproduce. The only example I have is a dump of https://github.com/tgstation/tgstation-server deadlocked at this point. For security reasons (bot tokens and SQL credentials) I cannot share it publicly.

### Expected Behavior

ResponderDispatchService.DisposeAsync() should complete eventually.

### Current Behavior

ResponderDispatchService.DisposeAsync() can deadlock waiting for a channel completion event that never comes.

### Library / Runtime Information

dotnet: 6.0
Remora.Discord: 2022.48.0
tgstation-server: 5.12.4
OS: Windows Server 2022

**Comment by Cyberboss** [comment]
Also the `.Completion` event won't fire if there are items still in the channel https://stackoverflow.com/a/66521303

**Comment by VelvetToroyashi** [comment]
Quite the peculiar set of issues, that's for sure. I've been hoping to rewrite mass swaths of Remora's codebase<sup>[1][2]<sup>, so I suppose I'll definitely tack this onto the list; rewriting dispatch would certainly be a worthwhile investment based on my investigations<sup>[3]</sup>

<sup>1</sup> #254
<sup>2</sup> [Remora.Commands PR](https://github.com/Remora/Remora.Commands/pulls/20)
<sup>3</sup> [Discussion in the Discord](https://discord.com/channels/789912892426027039/789912892899459104/1081254728752709673)

**Comment by Cyberboss** [comment]
This hacky reflection workaround was able to solve our issue: https://github.com/tgstation/tgstation-server/pull/1509

**Comment by Nihlus** [comment]
Interesting - thank you for the in-depth analysis. I've pushed a suggested fix to the `deadlock-fix` branch, which should alleviate the problem and fix another issue I uncovered. Please take a look when you have time.

**Comment by Cyberboss** [comment]
I've integrated this in my software and haven't heard the same bug report, so it looks to be working

**Comment by Nihlus** [comment]
Excellent!
