### ISSUE TITLE
[Bug]: Dependency Injection error is swallowed when trying to resolve commands and interactions

### ISSUE THREAD

**Issue by igorquintaes** [Remora/Remora.Discord#306]
### Description

If you forget to add some dependency and a command/interaction needs it, there is none error neither log, it is just swallowed.

### Steps to Reproduce

- Register command,
- Register interaction (modal ex)
- Write a code to command call the interaction
- Inside interaction class, put in ctor a unregistered dependency

### Expected Behavior

Thrown an exception, block request, or even log error in somewhere; What be more appropriate by lib design. Just don't swallow the error.

### Current Behavior

Execution finished (like a modal closing after sent) and nothing happens.

### Library / Runtime Information

Found in a project using:

Remora.Discord - Latest
.NET - 7 

Additional info: I spoke with jax and Velvet in Discord support channel about this issue.

**Comment by Nihlus** [comment]
The latest code should fix this issue. Could you test with the latest development package from the nuget feed?

**Comment by igorquintaes** [comment]
Just tried with `2023.3.0-github5433142973` version, but it is still swallowing the whole thing. I am going to write a simple repro project

**Comment by igorquintaes** [comment]
I am very sorry. The issue does not looks related to Remora, but to [Scrutor](https://github.com/khellang/Scrutor). It happens while we try to decorate some dependency with an unresolved decoration (using same interface). I am going to seek help there to make injection errors like this easy to detect.
